### PR TITLE
[WIP] Py2to3

### PR DESCRIPTION
**Pull request by christian34**
I went through a first round or modernisation following https://portingguide.readthedocs.io/en/latest/index.html. Hope that it helps !

I apply all patches (one per commit), except two, that need more advanced skills:
- in pkgmanager.py, arround line 900 there are long types declared and used with bit shifts : to be recoded to avoid usage of no longer available long type in py3
- applying libmodernize.fixes_fix_open emulate the python 3 open function, but results in a lot of errors due to string encoding, that I did not manage to solve : to be apllied again and fixed !

Then we can start testing python 3 !

### CODE REVIEW

**Comment by pradal** [comment]
Thks Christian!
Have you already run the tests? Are they passing?

**Comment by christian34** [comment]
Yes, all tests passed with nosetests in my env. I will add some fix for the CI !

**Comment by pradal** [comment]
Congats! You are now a Python master

Le 25/01/2020 à 14:43, Christian Fournier a écrit :

**Comment by christian34** [comment]
@pradal : test seems okay on linux/os . May be worth to try on appveyor ?(I dont know how to reactivate appveyor-ci). P2/Py3 merge is close !

**Pull request merged**
